### ISSUE TITLE
mediapipeのドキュメントが見つからない

### ISSUE THREAD

**Issue by Namacha411** [2021-NITGC-4J-H/auto-attendance-check#28]
mediapipeのドキュメントが見つからない
apiリファレンスでもC++との対応でもなんでもいいのでドキュメントがほしい

**Comment by Namacha411** [comment]
参考になりそうなもの
- <https://github.com/google/mediapipe/tree/master/mediapipe/framework>
- <https://google.github.io/mediapipe/getting_started/python_framework.html>
- <https://google.github.io/mediapipe/framework_concepts/framework_concepts.html>

**Comment by Omusubi0123** [comment]
作成完了
